// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4nmXeFVOvygpfO05i0IrSEL9l56D_VGo',
    appId: '1:26145555943:web:0b186d1f0dcb61b1b62942',
    messagingSenderId: '26145555943',
    projectId: 'elapas-ed733',
    authDomain: 'elapas-ed733.firebaseapp.com',
    storageBucket: 'elapas-ed733.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40uy8CkOsffXp88Om3jAXXxMqfiTkVyY',
    appId: '1:26145555943:android:e998b1488f762f7cb62942',
    messagingSenderId: '26145555943',
    projectId: 'elapas-ed733',
    storageBucket: 'elapas-ed733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTE5wg6xG6wioHXGTjIwDC888Yl2HlOpg',
    appId: '1:26145555943:ios:5ffda740b13a362cb62942',
    messagingSenderId: '26145555943',
    projectId: 'elapas-ed733',
    storageBucket: 'elapas-ed733.firebasestorage.app',
    iosBundleId: 'com.example.elapasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTE5wg6xG6wioHXGTjIwDC888Yl2HlOpg',
    appId: '1:26145555943:ios:5ffda740b13a362cb62942',
    messagingSenderId: '26145555943',
    projectId: 'elapas-ed733',
    storageBucket: 'elapas-ed733.firebasestorage.app',
    iosBundleId: 'com.example.elapasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4nmXeFVOvygpfO05i0IrSEL9l56D_VGo',
    appId: '1:26145555943:web:4758f7f80e37d564b62942',
    messagingSenderId: '26145555943',
    projectId: 'elapas-ed733',
    authDomain: 'elapas-ed733.firebaseapp.com',
    storageBucket: 'elapas-ed733.firebasestorage.app',
  );
}
